coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 85%

  ignore:
    - "tests/*"
    - "scripts/*"
    - "examples/*"
    - "fonts/*"
    - "output_images/*"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
